-- m001: 초기 스키마 (docs/db-schema.md §4.2 + §4.3에서 추출 — 정본은 문서)
-- 2026-07-07 Supabase 적용 완료

-- kokalim postgres ddl v1
CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- BY DEFAULT: id=0 예약행 삽입 허용
  created_at    timestamptz NOT NULL DEFAULT now(),
  briefing_time TIME                                                  -- 'HH:MM' KST 해석, NULL=브리핑 미수신 (m002)
);

CREATE TABLE identities (
  user_id           BIGINT NOT NULL REFERENCES users(id),
  provider          TEXT NOT NULL CHECK (provider IN ('toss','kakao','telegram')),  -- telegram: m002
  provider_user_id  TEXT NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, provider),
  UNIQUE (provider, provider_user_id)
);

CREATE TABLE companies (
  ticker   TEXT PRIMARY KEY,
  name     TEXT NOT NULL,
  market   TEXT NOT NULL,
  aliases  JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE watchlist (
  user_id         BIGINT NOT NULL REFERENCES users(id),
  ticker          TEXT NOT NULL REFERENCES companies(ticker),
  created_at      timestamptz NOT NULL DEFAULT now(),
  notify_enabled  BOOLEAN NOT NULL DEFAULT false,
  notify_types    JSONB NOT NULL DEFAULT '["news","disclosure","price"]',
  toss_consent_at timestamptz,
  PRIMARY KEY (user_id, ticker)
);

CREATE TABLE events (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ticker        TEXT NOT NULL REFERENCES companies(ticker),
  type          TEXT NOT NULL CHECK (type IN ('news','disclosure','price')),
  cluster_key   TEXT NOT NULL,
  headline      TEXT NOT NULL,
  summary_line  TEXT NOT NULL DEFAULT '',
  url           TEXT NOT NULL,
  source        TEXT NOT NULL DEFAULT '',
  source_count  INTEGER NOT NULL DEFAULT 1,
  keyword_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  urgency_score DOUBLE PRECISION,
  reason        TEXT NOT NULL DEFAULT '',
  published_at  timestamptz NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ticker, type, cluster_key)
);

CREATE TABLE deliveries (
  event_id            BIGINT NOT NULL REFERENCES events(id),
  user_id             BIGINT NOT NULL REFERENCES users(id),
  channel             TEXT NOT NULL CHECK (channel IN ('toss','telegram','console')),
  status              TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','sent','failed','skipped')),
  fail_reason         TEXT,
  provider_content_id TEXT,
  attempt             INTEGER NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now(),
  sent_at             timestamptz,
  PRIMARY KEY (event_id, user_id, channel)
);

CREATE TABLE saved_news (
  user_id   BIGINT NOT NULL REFERENCES users(id),
  event_id  BIGINT NOT NULL REFERENCES events(id),
  saved_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, event_id)
);

CREATE TABLE briefings (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id),
  date        DATE NOT NULL,
  payload     JSONB NOT NULL,
  sent_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, date)
);

CREATE TABLE situations (
  unit_key     TEXT PRIMARY KEY,
  company      TEXT NOT NULL,
  entity_name  TEXT NOT NULL,
  kind         TEXT CHECK (kind IN ('self','related','theme')),
  summary      TEXT NOT NULL DEFAULT '',
  stance       TEXT NOT NULL DEFAULT 'neutral'
               CHECK (stance IN ('positive','negative','neutral')),
  updated_at   timestamptz
);

CREATE TABLE situation_timeline (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  unit_key    TEXT NOT NULL REFERENCES situations(unit_key),
  at          timestamptz NOT NULL,
  change      TEXT NOT NULL,
  importance  INTEGER NOT NULL CHECK (importance BETWEEN 0 AND 10)
);

CREATE TABLE kakao_messages (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id),
  direction   TEXT NOT NULL CHECK (direction IN ('in','out')),
  text        TEXT NOT NULL,
  intent      TEXT,
  payload     JSONB,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE legacy_seen (
  title_hash  TEXT PRIMARY KEY,
  seen_at     timestamptz NOT NULL
);

CREATE INDEX idx_watchlist_fanout   ON watchlist (ticker) WHERE notify_enabled;
CREATE INDEX idx_identities_user    ON identities (user_id);
CREATE INDEX idx_events_ticker_pub  ON events (ticker, published_at DESC);
CREATE INDEX idx_deliveries_queue   ON deliveries (channel, created_at) WHERE status = 'pending';
CREATE INDEX idx_saved_user         ON saved_news (user_id, saved_at DESC);
CREATE INDEX idx_timeline_unit      ON situation_timeline (unit_key, at DESC);
CREATE INDEX idx_kakao_user_time    ON kakao_messages (user_id, created_at);
CREATE INDEX idx_kakao_created      ON kakao_messages (created_at);
CREATE INDEX idx_companies_name     ON companies (name);

INSERT INTO users (id) VALUES (0);  -- 단일유저 CLI 예약

-- kokalim supabase rls guard v1 — §4.2 DDL 직후 실행 (정책은 만들지 않는다 = 전부 거부)
ALTER TABLE users              ENABLE ROW LEVEL SECURITY;
ALTER TABLE identities         ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies          ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchlist          ENABLE ROW LEVEL SECURITY;
ALTER TABLE events             ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries         ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_news         ENABLE ROW LEVEL SECURITY;
ALTER TABLE briefings          ENABLE ROW LEVEL SECURITY;
ALTER TABLE situations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE situation_timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE kakao_messages     ENABLE ROW LEVEL SECURITY;
ALTER TABLE legacy_seen        ENABLE ROW LEVEL SECURITY;
